### ISSUE TITLE
PrinterHoming instance has no attribute 'probing_move

### ISSUE THREAD

**Issue by bieber** [protoloft/klipper_z_calibration#8]
I tried setting this up on my Voron 2.4 with klipper v0.9.1-299-gb0f94e50.  At first I ran into issue #5, but I just removed the logging code that used that call and that got G28 running fine.  I set up the following z_calibration config:

```
[z_calibration]                                                               
probe_nozzle_x: 232                                                           
probe_nozzle_y: 350                                                           
probe_switch_x: 227                                                           
probe_switch_y: 330.25                                                        
switch_offset: 0.46                                                           
```

and the following CALIBRATE_Z macro, using a klicky probe:

```
[gcode_macro CALIBRATE_Z]                                                     
rename_existing: BASE_CALIBRATE_Z                                             
gcode:                                                                        
    M117 Z-Calibration..                                                      
    Attach_Probe                                                              
    BASE_CALIBRATE_Z                                                          
    Dock_Probe                                                                
    M117                                                                      
```

When I tried running `CALIBRATE_Z`, however, I got the following error in the printer terminal:

```
Recv: !! Internal error on command:"BASE_CALIBRATE_Z"
Recv: !! Internal error on command:"CALIBRATE_Z"
```

This is the stack trace I got from klippy.log:

```
Internal error on command:"BASE_CALIBRATE_Z"
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 182, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 120, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/pi/klipper/klippy/gcode.py", line 120, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/pi/klipper/klippy/extras/z_calibration.py", line 137, in cmd_CALIBRATE_Z
    state.calibrate_z()
  File "/home/pi/klipper/klippy/extras/z_calibration.py", line 312, in calibrate_z
    nozzle_zero = self._probe_on_z_endstop(self.helper.probe_nozzle_site)
  File "/home/pi/klipper/klippy/extras/z_calibration.py", line 266, in _probe_on_z_endstop
    self.helper.second_speed)
  File "/home/pi/klipper/klippy/extras/z_calibration.py", line 190, in _probe
    curpos = phoming.probing_move(mcu_endstop, pos, speed)
AttributeError: PrinterHoming instance has no attribute 'probing_move'
Transition to shutdown state: Internal error on command:"BASE_CALIBRATE_Z"
```

Any idea what may have caused this?  My klipper install hasn't been updated since I first set up the printer, do I maybe need to update it?

**Comment by bieber** [comment]
Looks like it was just the klipper version that was the problem, updated and now it's working
